// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ParseLog(arg1:string):Promise<Array<string>>;

export function ParseMessage(arg1:string):Promise<models.ParsedMessage>;

export function ParseMultipleMessages(arg1:Array<string>):Promise<Array<models.ParsedMessage>>;
