// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function FilterLog(arg1:string):Promise<Array<main.Message>>;

export function ListTemplateFiles():Promise<Array<string>>;

export function LoadTemplate(arg1:string):Promise<void>;

export function ParseAndValidateMessage(arg1:string):Promise<models.ParsedMessage>;

export function ParseJsonMessage(arg1:string):Promise<models.ParsedMessage>;

export function ParseSimpleMessage(arg1:string):Promise<models.ParsedMessage>;
