// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParseLog(arg1) {
  return window['go']['main']['App']['ParseLog'](arg1);
}

export function ParseMessage(arg1) {
  return window['go']['main']['App']['ParseMessage'](arg1);
}

export function ParseMultipleMessages(arg1) {
  return window['go']['main']['App']['ParseMultipleMessages'](arg1);
}
