// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilterLog(arg1) {
  return window['go']['main']['App']['FilterLog'](arg1);
}

export function ListTemplateFiles() {
  return window['go']['main']['App']['ListTemplateFiles']();
}

export function LoadTemplate(arg1) {
  return window['go']['main']['App']['LoadTemplate'](arg1);
}

export function ParseAndValidateMessage(arg1) {
  return window['go']['main']['App']['ParseAndValidateMessage'](arg1);
}

export function ParseJsonMessage(arg1) {
  return window['go']['main']['App']['ParseJsonMessage'](arg1);
}

export function ParseSimpleMessage(arg1) {
  return window['go']['main']['App']['ParseSimpleMessage'](arg1);
}
