name: Send POST Request to auto build on CloudFlare

on:
  workflow_dispatch:

jobs:
  post_request:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP POST Request
        run: |
          curl -X POST "${{ secrets.API_BUILD_ISO8583_CLOUDFLARE }}"